import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";

const About: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>about</div>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </Layout>
  );
};

export async function getStaticProps() {
  // const res = await fetch('https://.../posts')
  const posts = { a: "b" };

  return {
    props: {
      posts,
    },
  };
}

export default About;
